#!/usr/bin/env node
/**
 * DDL 转换回归测试 — 6 个方向, 每个用例覆盖:
 *   CREATE TABLE (多种列类型, PK, UK, FK, DEFAULT, NOT NULL, 注释, 自增)
 *   CREATE INDEX
 *   CREATE VIEW (函数转换, JOIN, 聚合, WITH CHECK OPTION / WITH READ ONLY)
 *   COMMENT ON
 *
 * 生成的 SQL 文件可直接在真实数据库执行验证.
 */

var fs = require('fs');

/* ===== 加载引擎 ===== */
var samplesCode = fs.readFileSync(__dirname + '/samples.js', 'utf8').replace(/\bconst\b/g, 'var');
eval(samplesCode);
var rulesCode = fs.readFileSync(__dirname + '/rules.js', 'utf8').replace(/\bconst\b/g, 'var');
eval(rulesCode);
var localStorage = { getItem: function () { return null; }, setItem: function () {} };
var appCode = fs.readFileSync(__dirname + '/app.js', 'utf8');
var vueStart = appCode.indexOf('/* ===== VUE 3 APP ===== */');
if (vueStart > 0) appCode = appCode.substring(0, vueStart);
appCode = appCode.replace(/\bconst\b/g, 'var');
eval(appCode);

/* ===== 6 个测试用例 ===== */
var CASES = [];

// ---------- 1. Oracle → MySQL ----------
CASES.push({
  name: 'Oracle → MySQL',
  from: 'oracle', to: 'mysql',
  input: [
    "CREATE TABLE T_ORDER (",
    "    ORDER_ID      NUMBER(18)       GENERATED BY DEFAULT ON NULL AS IDENTITY,",
    "    USER_ID       NUMBER(18)       NOT NULL,",
    "    ORDER_NO      VARCHAR2(32)     NOT NULL,",
    "    PRODUCT_NAME  NVARCHAR2(200),",
    "    QUANTITY      NUMBER(10)       DEFAULT 1,",
    "    UNIT_PRICE    NUMBER(18,2),",
    "    TOTAL_AMT     NUMBER(18,2)     DEFAULT 0,",
    "    STATUS        CHAR(1)          DEFAULT 'N',",
    "    MEMO          CLOB,",
    "    PHOTO         BLOB,",
    "    IS_PAID       NUMBER(1)        DEFAULT 0,",
    "    CREATE_TIME   TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,",
    "    UPDATE_TIME   TIMESTAMP,",
    "    CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_ID)",
    ");",
    "",
    "COMMENT ON TABLE T_ORDER IS '订单主表';",
    "COMMENT ON COLUMN T_ORDER.ORDER_ID IS '订单ID-自增主键';",
    "COMMENT ON COLUMN T_ORDER.ORDER_NO IS '订单编号';",
    "COMMENT ON COLUMN T_ORDER.TOTAL_AMT IS '订单总金额';",
    "COMMENT ON COLUMN T_ORDER.STATUS IS '状态: N-新建 P-处理中 D-完成';",
    "",
    "CREATE UNIQUE INDEX IDX_UNI_ORDER_NO ON T_ORDER(ORDER_NO);",
    "CREATE INDEX IDX_ORDER_USER ON T_ORDER(USER_ID, CREATE_TIME);",
    "",
    "CREATE TABLE T_ORDER_ITEM (",
    "    ITEM_ID    NUMBER(18)    NOT NULL,",
    "    ORDER_ID   NUMBER(18)    NOT NULL,",
    "    SKU        VARCHAR2(64),",
    "    QTY        NUMBER(10)    DEFAULT 1,",
    "    PRICE      NUMBER(18,2),",
    "    CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (ITEM_ID),",
    "    CONSTRAINT FK_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES T_ORDER(ORDER_ID) ON DELETE CASCADE",
    ");",
    "",
    "COMMENT ON TABLE T_ORDER_ITEM IS '订单明细表';",
    "",
    "CREATE OR REPLACE VIEW V_ORDER_SUMMARY AS",
    "SELECT O.ORDER_ID, O.ORDER_NO, O.USER_ID,",
    "       NVL(O.TOTAL_AMT, 0) AS TOTAL_AMT,",
    "       DECODE(O.STATUS, 'N', '新建', 'P', '处理中', 'D', '已完成', '未知') AS STATUS_TEXT,",
    "       TO_CHAR(O.CREATE_TIME, 'YYYY-MM-DD HH24:MI:SS') AS CREATED,",
    "       COUNT(I.ITEM_ID) AS ITEM_COUNT",
    "  FROM T_ORDER O",
    "  LEFT JOIN T_ORDER_ITEM I ON O.ORDER_ID = I.ORDER_ID",
    " GROUP BY O.ORDER_ID, O.ORDER_NO, O.USER_ID, O.TOTAL_AMT, O.STATUS, O.CREATE_TIME;",
    "",
    "COMMENT ON TABLE V_ORDER_SUMMARY IS '订单汇总视图';",
    "",
    "CREATE OR REPLACE VIEW V_PAID_ORDERS AS",
    "SELECT ORDER_ID, ORDER_NO, TOTAL_AMT FROM T_ORDER WHERE IS_PAID = 1",
    "  WITH READ ONLY;",
    "",
    "COMMENT ON TABLE V_PAID_ORDERS IS '已支付订单只读视图';"
  ].join('\n'),
  expect: [
    // 表结构
    { pattern: /AUTO_INCREMENT/i,                  label: 'IDENTITY → AUTO_INCREMENT' },
    { pattern: /BIGINT/i,                          label: 'NUMBER(18) → BIGINT' },
    { pattern: /VARCHAR\(32\)/i,                   label: 'VARCHAR2(32) → VARCHAR(32)' },
    { pattern: /LONGTEXT/i,                        label: 'CLOB → LONGTEXT' },
    { pattern: /LONGBLOB/i,                        label: 'BLOB → LONGBLOB' },
    { pattern: /DECIMAL\(18,2\)/i,                 label: 'NUMBER(18,2) → DECIMAL(18,2)' },
    { pattern: /DEFAULT CURRENT_TIMESTAMP/i,       label: 'SYSTIMESTAMP → CURRENT_TIMESTAMP' },
    { pattern: /COMMENT='订单主表'/,               label: '表注释内联' },
    { pattern: /COMMENT\s+'订单ID/,                label: '列注释内联' },
    { pattern: /UNIQUE KEY.*idx_uni_order_no/i,    label: 'UNIQUE INDEX 转换' },
    { pattern: /ON DELETE CASCADE/i,               label: 'FK ON DELETE CASCADE 保留' },
    // 视图
    { pattern: /CREATE OR REPLACE VIEW/i,          label: 'CREATE VIEW 生成' },
    { pattern: /IFNULL\(/i,                        label: 'NVL → IFNULL' },
    { pattern: /CASE.*WHEN.*'N'.*THEN.*'新建'/i,   label: 'DECODE → CASE WHEN' },
    { pattern: /DATE_FORMAT\(/i,                   label: 'TO_CHAR → DATE_FORMAT' },
    { pattern: /\nWITH READ ONLY\s*;/i, negate: true, label: 'WITH READ ONLY 语法已移除 (MySQL不支持)' },
    { pattern: /注意.*MySQL.*不支持.*WITH READ ONLY/,label: 'READ ONLY 兼容性注释' },
  ]
});

// ---------- 2. Oracle → PostgreSQL ----------
CASES.push({
  name: 'Oracle → PostgreSQL',
  from: 'oracle', to: 'postgresql',
  input: [
    "CREATE TABLE T_ACCOUNT (",
    "    ACCT_ID       NUMBER(18)       GENERATED BY DEFAULT ON NULL AS IDENTITY,",
    "    ACCT_NO       VARCHAR2(20)     NOT NULL,",
    "    HOLDER_NAME   NVARCHAR2(100),",
    "    BALANCE       NUMBER(18,4)     DEFAULT 0,",
    "    IS_ACTIVE     NUMBER(1)        DEFAULT 1,",
    "    OPEN_DATE     DATE,",
    "    LAST_TXN      TIMESTAMP        DEFAULT SYSTIMESTAMP,",
    "    NOTES         CLOB,",
    "    RAW_DATA      RAW(500),",
    "    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCT_ID)",
    ");",
    "",
    "COMMENT ON TABLE T_ACCOUNT IS '账户信息表';",
    "COMMENT ON COLUMN T_ACCOUNT.BALANCE IS '余额(精度4位)';",
    "",
    "CREATE UNIQUE INDEX IDX_ACCT_NO ON T_ACCOUNT(ACCT_NO);",
    "CREATE INDEX IDX_ACCT_HOLDER ON T_ACCOUNT(HOLDER_NAME);",
    "",
    "CREATE OR REPLACE VIEW V_ACTIVE_ACCTS AS",
    "SELECT ACCT_ID, ACCT_NO, HOLDER_NAME,",
    "       NVL(BALANCE, 0) AS BALANCE,",
    "       NVL2(NOTES, '有备注', '无备注') AS HAS_NOTES,",
    "       TO_CHAR(OPEN_DATE, 'YYYY-MM-DD') AS OPENED",
    "  FROM T_ACCOUNT",
    " WHERE IS_ACTIVE = 1;",
    "",
    "COMMENT ON TABLE V_ACTIVE_ACCTS IS '活跃账户视图';"
  ].join('\n'),
  expect: [
    { pattern: /BIGSERIAL/i,                       label: 'IDENTITY → BIGSERIAL' },
    { pattern: /NUMERIC\(18,4\)/i,                 label: 'NUMBER(18,4) → NUMERIC(18,4)' },
    { pattern: /\bTEXT\b/,                         label: 'CLOB → TEXT' },
    { pattern: /\bBYTEA\b/i,                       label: 'RAW → BYTEA' },
    { pattern: /\bTIMESTAMP\b/i,                   label: 'DATE → TIMESTAMP' },
    { pattern: /DEFAULT CLOCK_TIMESTAMP\(\)/i,     label: 'SYSTIMESTAMP → CLOCK_TIMESTAMP()' },
    { pattern: /COMMENT ON TABLE t_account/i,      label: 'COMMENT ON TABLE' },
    { pattern: /COMMENT ON COLUMN/i,               label: 'COMMENT ON COLUMN' },
    { pattern: /CREATE UNIQUE INDEX/i,             label: 'UNIQUE INDEX 保留' },
    // 视图
    { pattern: /COALESCE\(/i,                      label: 'NVL → COALESCE' },
    { pattern: /CASE\s+WHEN\s+/i,                  label: 'NVL2 → CASE WHEN' },
    { pattern: /COMMENT ON VIEW/i,                 label: 'COMMENT ON VIEW (PG语法)' },
  ]
});

// ---------- 3. MySQL → Oracle ----------
CASES.push({
  name: 'MySQL → Oracle',
  from: 'mysql', to: 'oracle',
  input: [
    "CREATE TABLE t_product (",
    "    product_id    BIGINT           NOT NULL AUTO_INCREMENT,",
    "    sku           VARCHAR(64)      NOT NULL,",
    "    name          VARCHAR(200)     CHARACTER SET utf8mb4,",
    "    category      CHAR(4)          DEFAULT 'MISC',",
    "    price         DECIMAL(12,2)    DEFAULT 0,",
    "    stock         INT              DEFAULT 0,",
    "    is_on_sale    TINYINT(1)       DEFAULT 1,",
    "    description   LONGTEXT,",
    "    image         LONGBLOB,",
    "    created_at    TIMESTAMP(6)     DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,",
    "    updated_at    TIMESTAMP(6)     NULL ON UPDATE CURRENT_TIMESTAMP(6),",
    "    PRIMARY KEY (product_id),",
    "    UNIQUE KEY idx_sku (sku),",
    "    KEY idx_category (category, price)",
    ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "  COMMENT='产品信息表';",
    "",
    "CREATE TABLE t_review (",
    "    review_id     BIGINT       NOT NULL AUTO_INCREMENT,",
    "    product_id    BIGINT       NOT NULL,",
    "    rating        TINYINT      DEFAULT 5,",
    "    content       TEXT,",
    "    created_at    DATETIME     DEFAULT NOW(),",
    "    PRIMARY KEY (review_id),",
    "    CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES t_product(product_id) ON DELETE CASCADE",
    ") ENGINE=InnoDB COMMENT='产品评价表';",
    "",
    "CREATE OR REPLACE VIEW v_product_stats AS",
    "SELECT p.product_id, p.sku, p.name,",
    "       IFNULL(p.price, 0) AS price,",
    "       IFNULL(AVG(r.rating), 0) AS avg_rating,",
    "       COUNT(r.review_id) AS review_count,",
    "       DATE_FORMAT(p.created_at, '%Y-%m-%d') AS listed_date",
    "  FROM t_product p",
    "  LEFT JOIN t_review r ON p.product_id = r.product_id",
    " GROUP BY p.product_id, p.sku, p.name, p.price, p.created_at;",
    "",
    "CREATE OR REPLACE VIEW v_on_sale AS",
    "SELECT product_id, sku, name, price FROM t_product WHERE is_on_sale = 1",
    "  WITH CASCADED CHECK OPTION;"
  ].join('\n'),
  expect: [
    { pattern: /GENERATED BY DEFAULT ON NULL AS IDENTITY/i, label: 'AUTO_INCREMENT → IDENTITY' },
    { pattern: /NUMBER\(18\)/i,                    label: 'BIGINT → NUMBER(18)' },
    { pattern: /VARCHAR2\(64\)/i,                  label: 'VARCHAR(64) → VARCHAR2(64)' },
    { pattern: /NUMBER\(12,2\)/i,                  label: 'DECIMAL(12,2) → NUMBER(12,2)' },
    { pattern: /NUMBER\(1\)/i,                     label: 'TINYINT(1) → NUMBER(1)' },
    { pattern: /\bCLOB\b/,                         label: 'LONGTEXT → CLOB' },
    { pattern: /\bBLOB\b/,                         label: 'LONGBLOB → BLOB' },
    { pattern: /DEFAULT SYSTIMESTAMP/i,             label: 'CURRENT_TIMESTAMP → SYSTIMESTAMP' },
    { pattern: /COMMENT ON TABLE.*'产品信息表'/i,  label: 'COMMENT ON TABLE 生成' },
    { pattern: /ON DELETE CASCADE/i,               label: 'FK CASCADE 保留' },
    // 视图
    { pattern: /\bNVL\(/i,                         label: 'IFNULL → NVL' },
    { pattern: /TO_CHAR\(/i,                       label: 'DATE_FORMAT → TO_CHAR' },
    { pattern: /WITH CHECK OPTION/i,               label: 'CHECK OPTION 保留' },
  ]
});

// ---------- 4. MySQL → PostgreSQL ----------
CASES.push({
  name: 'MySQL → PostgreSQL',
  from: 'mysql', to: 'postgresql',
  input: [
    "CREATE TABLE t_employee (",
    "    emp_id        BIGINT           NOT NULL AUTO_INCREMENT,",
    "    emp_no        VARCHAR(20)      NOT NULL,",
    "    full_name     VARCHAR(100),",
    "    department    VARCHAR(50)      DEFAULT 'General',",
    "    salary        DECIMAL(10,2)    DEFAULT 0,",
    "    hire_date     DATETIME         NOT NULL,",
    "    is_manager    TINYINT(1)       DEFAULT 0,",
    "    bio           MEDIUMTEXT,",
    "    avatar        MEDIUMBLOB,",
    "    created_at    TIMESTAMP(6)     DEFAULT CURRENT_TIMESTAMP(6),",
    "    PRIMARY KEY (emp_id),",
    "    UNIQUE KEY idx_emp_no (emp_no),",
    "    KEY idx_dept (department)",
    ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "  COMMENT='员工信息表';",
    "",
    "CREATE OR REPLACE VIEW v_managers AS",
    "SELECT emp_id, emp_no, full_name, department, salary,",
    "       IFNULL(department, '未分配') AS dept_display,",
    "       DATE_FORMAT(hire_date, '%Y-%m-%d') AS hire_date_str",
    "  FROM t_employee",
    " WHERE is_manager = 1;",
    "",
    "CREATE OR REPLACE VIEW v_dept_salary AS",
    "SELECT department,",
    "       COUNT(*) AS headcount,",
    "       IFNULL(SUM(salary), 0) AS total_salary,",
    "       IFNULL(AVG(salary), 0) AS avg_salary",
    "  FROM t_employee",
    " GROUP BY department",
    "  WITH CASCADED CHECK OPTION;"
  ].join('\n'),
  expect: [
    { pattern: /BIGSERIAL/i,                       label: 'AUTO_INCREMENT → BIGSERIAL' },
    { pattern: /\bBOOLEAN\b/i,                     label: 'TINYINT(1) → BOOLEAN' },
    { pattern: /NUMERIC\(10,2\)/i,                 label: 'DECIMAL(10,2) → NUMERIC(10,2)' },
    { pattern: /\bTEXT\b/,                         label: 'MEDIUMTEXT → TEXT' },
    { pattern: /\bBYTEA\b/i,                       label: 'MEDIUMBLOB → BYTEA' },
    { pattern: /\bTIMESTAMP\b/i,                   label: 'DATETIME → TIMESTAMP' },
    { pattern: /COMMENT ON TABLE.*'员工信息表'/i,  label: 'COMMENT ON TABLE' },
    { pattern: /CREATE UNIQUE INDEX/i,             label: 'UNIQUE KEY → UNIQUE INDEX' },
    // 视图
    { pattern: /COALESCE\(/i,                      label: 'IFNULL → COALESCE' },
    { pattern: /to_char\(/i,                       label: 'DATE_FORMAT → to_char' },
    { pattern: /WITH CASCADED CHECK OPTION/i,      label: 'CHECK OPTION 保留含类型' },
  ]
});

// ---------- 5. PostgreSQL → Oracle ----------
CASES.push({
  name: 'PostgreSQL → Oracle',
  from: 'postgresql', to: 'oracle',
  input: [
    "CREATE TABLE t_project (",
    "    project_id    BIGSERIAL        NOT NULL,",
    "    project_code  VARCHAR(30)      NOT NULL,",
    "    title         VARCHAR(200),",
    "    budget        NUMERIC(15,2)    DEFAULT 0,",
    "    is_active     BOOLEAN          DEFAULT TRUE,",
    "    start_date    TIMESTAMP,",
    "    description   TEXT,",
    "    attachment    BYTEA,",
    "    created_at    TIMESTAMP        DEFAULT CLOCK_TIMESTAMP() NOT NULL,",
    "    CONSTRAINT pk_project PRIMARY KEY (project_id)",
    ");",
    "",
    "COMMENT ON TABLE t_project IS '项目管理表';",
    "COMMENT ON COLUMN t_project.budget IS '项目预算';",
    "COMMENT ON COLUMN t_project.is_active IS '是否有效';",
    "",
    "CREATE UNIQUE INDEX idx_project_code ON t_project(project_code);",
    "CREATE INDEX idx_project_active ON t_project(is_active, start_date);",
    "",
    "CREATE TABLE t_task (",
    "    task_id       SERIAL           NOT NULL,",
    "    project_id    BIGINT           NOT NULL,",
    "    task_name     VARCHAR(100),",
    "    status        VARCHAR(20)      DEFAULT 'OPEN',",
    "    CONSTRAINT pk_task PRIMARY KEY (task_id),",
    "    CONSTRAINT fk_task_project FOREIGN KEY (project_id) REFERENCES t_project(project_id) ON DELETE CASCADE",
    ");",
    "",
    "COMMENT ON TABLE t_task IS '任务表';",
    "",
    "CREATE OR REPLACE VIEW v_project_overview AS",
    "SELECT p.project_id, p.project_code, p.title,",
    "       COALESCE(p.budget, 0) AS budget,",
    "       CASE WHEN p.is_active THEN '有效' ELSE '无效' END AS status,",
    "       COUNT(t.task_id) AS task_count,",
    "       TO_CHAR(p.created_at, 'YYYY-MM-DD') AS created",
    "  FROM t_project p",
    "  LEFT JOIN t_task t ON p.project_id = t.project_id",
    " GROUP BY p.project_id, p.project_code, p.title, p.budget, p.is_active, p.created_at;",
    "",
    "COMMENT ON VIEW v_project_overview IS '项目概览视图';",
    "",
    "CREATE OR REPLACE VIEW v_active_projects AS",
    "SELECT project_id, project_code, title, budget",
    "  FROM t_project WHERE is_active = TRUE",
    "  WITH LOCAL CHECK OPTION;",
    "",
    "COMMENT ON VIEW v_active_projects IS '活跃项目视图';"
  ].join('\n'),
  expect: [
    { pattern: /NUMBER\(18\)/i,                    label: 'BIGSERIAL → NUMBER(18) + IDENTITY' },
    { pattern: /GENERATED BY DEFAULT ON NULL AS IDENTITY/i, label: 'SERIAL → IDENTITY' },
    { pattern: /VARCHAR2\(30\)/i,                  label: 'VARCHAR(30) → VARCHAR2(30)' },
    { pattern: /NUMBER\(15,2\)/i,                  label: 'NUMERIC(15,2) → NUMBER(15,2)' },
    { pattern: /NUMBER\(1\)/i,                     label: 'BOOLEAN → NUMBER(1)' },
    { pattern: /\bCLOB\b/,                         label: 'TEXT → CLOB' },
    { pattern: /\bBLOB\b/,                         label: 'BYTEA → BLOB' },
    { pattern: /DEFAULT SYSTIMESTAMP/i,             label: 'CLOCK_TIMESTAMP() → SYSTIMESTAMP' },
    { pattern: /COMMENT ON TABLE.*'项目管理表'/i,  label: 'COMMENT ON TABLE' },
    { pattern: /COMMENT ON COLUMN/i,               label: 'COMMENT ON COLUMN' },
    { pattern: /ON DELETE CASCADE/i,               label: 'FK CASCADE' },
    // 视图
    { pattern: /\bNVL\(/i,                         label: 'COALESCE → NVL' },
    { pattern: /COMMENT ON TABLE.*V_PROJECT_OVERVIEW/i, label: 'COMMENT ON VIEW → COMMENT ON TABLE' },
    { pattern: /WITH CHECK OPTION/i,               label: 'CHECK OPTION → Oracle' },
  ]
});

// ---------- 6. PostgreSQL → MySQL ----------
CASES.push({
  name: 'PostgreSQL → MySQL',
  from: 'postgresql', to: 'mysql',
  input: [
    "CREATE TABLE t_article (",
    "    article_id    BIGSERIAL        NOT NULL,",
    "    slug          VARCHAR(100)     NOT NULL,",
    "    title         VARCHAR(200),",
    "    author        VARCHAR(80),",
    "    word_count    INTEGER          DEFAULT 0,",
    "    score         NUMERIC(5,2),",
    "    is_published  BOOLEAN          DEFAULT FALSE,",
    "    body          TEXT,",
    "    cover_img     BYTEA,",
    "    published_at  TIMESTAMP,",
    "    created_at    TIMESTAMP        DEFAULT CLOCK_TIMESTAMP() NOT NULL,",
    "    CONSTRAINT pk_article PRIMARY KEY (article_id)",
    ");",
    "",
    "COMMENT ON TABLE t_article IS '文章表';",
    "COMMENT ON COLUMN t_article.slug IS 'URL友好标识';",
    "COMMENT ON COLUMN t_article.score IS '评分';",
    "",
    "CREATE UNIQUE INDEX idx_slug ON t_article(slug);",
    "CREATE INDEX idx_author ON t_article(author);",
    "CREATE INDEX idx_published ON t_article(is_published, published_at);",
    "",
    "CREATE TABLE t_tag (",
    "    tag_id        SERIAL           NOT NULL,",
    "    article_id    BIGINT           NOT NULL,",
    "    tag_name      VARCHAR(50),",
    "    CONSTRAINT pk_tag PRIMARY KEY (tag_id),",
    "    CONSTRAINT fk_tag_article FOREIGN KEY (article_id) REFERENCES t_article(article_id) ON DELETE CASCADE ON UPDATE CASCADE",
    ");",
    "",
    "CREATE OR REPLACE VIEW v_published_articles AS",
    "SELECT a.article_id, a.slug, a.title, a.author,",
    "       COALESCE(a.score, 0) AS score,",
    "       a.word_count,",
    "       COUNT(t.tag_id) AS tag_count,",
    "       TO_CHAR(a.published_at, 'YYYY-MM-DD') AS pub_date",
    "  FROM t_article a",
    "  LEFT JOIN t_tag t ON a.article_id = t.article_id",
    " WHERE a.is_published = TRUE",
    " GROUP BY a.article_id, a.slug, a.title, a.author, a.score, a.word_count, a.published_at;",
    "",
    "CREATE OR REPLACE VIEW v_top_articles AS",
    "SELECT article_id, slug, title, score",
    "  FROM t_article",
    " WHERE score >= 4.0 AND is_published = TRUE",
    "  WITH LOCAL CHECK OPTION;"
  ].join('\n'),
  expect: [
    { pattern: /BIGINT.*AUTO_INCREMENT/i,          label: 'BIGSERIAL → BIGINT AUTO_INCREMENT' },
    { pattern: /INT.*AUTO_INCREMENT/i,             label: 'SERIAL → INT AUTO_INCREMENT' },
    { pattern: /VARCHAR\(100\)/i,                  label: 'VARCHAR 保留' },
    { pattern: /DECIMAL\(5,2\)/i,                  label: 'NUMERIC(5,2) → DECIMAL(5,2)' },
    { pattern: /LONGTEXT/i,                        label: 'TEXT → LONGTEXT' },
    { pattern: /LONGBLOB/i,                        label: 'BYTEA → LONGBLOB' },
    { pattern: /DEFAULT CURRENT_TIMESTAMP/i,       label: 'CLOCK_TIMESTAMP → CURRENT_TIMESTAMP' },
    { pattern: /COMMENT='文章表'/,                 label: '表注释内联' },
    { pattern: /COMMENT\s+'URL友好/,               label: '列注释内联' },
    { pattern: /ON DELETE CASCADE/i,               label: 'FK ON DELETE' },
    { pattern: /ON UPDATE CASCADE/i,               label: 'FK ON UPDATE' },
    // 视图
    { pattern: /IFNULL\(/i,                        label: 'COALESCE → IFNULL' },
    { pattern: /DATE_FORMAT\(/i,                   label: 'TO_CHAR → DATE_FORMAT' },
    { pattern: /WITH LOCAL CHECK OPTION/i,         label: 'CHECK OPTION 保留含类型' },
  ]
});

/* ===== 执行测试 ===== */
var totalPass = 0, totalFail = 0, totalCases = 0;
var outputDir = __dirname + '/test_output';
try { fs.mkdirSync(outputDir); } catch (e) {}

console.log('╔══════════════════════════════════════════════════════════╗');
console.log('║       DDL 转换回归测试 — 6 方向 × 真实数据库可执行      ║');
console.log('╚══════════════════════════════════════════════════════════╝\n');

for (var ci = 0; ci < CASES.length; ci++) {
  var tc = CASES[ci];
  var output;
  try {
    output = convertDDL(tc.input, tc.from, tc.to);
  } catch (e) {
    output = '-- FATAL: ' + e.message;
  }

  // 保存到文件
  var fileName = (ci + 1) + '_' + tc.from + '_to_' + tc.to + '.sql';
  // 在输出文件头部增加目标库执行提示
  var dbHint = '';
  if (tc.to === 'oracle') dbHint = '-- 目标数据库: Oracle 19c+ (sqlplus / SQL Developer 执行)\n';
  else if (tc.to === 'mysql') dbHint = '-- 目标数据库: MySQL 8.0+ (mysql CLI / Workbench 执行)\n';
  else dbHint = '-- 目标数据库: PostgreSQL 14+ (psql / pgAdmin 执行)\n';
  fs.writeFileSync(outputDir + '/' + fileName, dbHint + output, 'utf8');

  // 断言检查
  var pass = 0, fail = 0, details = [];
  for (var ei = 0; ei < tc.expect.length; ei++) {
    var ex = tc.expect[ei];
    var matched = ex.pattern.test(output);
    if (ex.negate) matched = !matched;
    totalCases++;
    if (matched) {
      pass++; totalPass++;
      details.push('  ✓ ' + ex.label);
    } else {
      fail++; totalFail++;
      details.push('  ✗ ' + ex.label + '  [FAIL: ' + ex.pattern + ']');
    }
  }

  var status = fail === 0 ? 'PASS' : 'FAIL';
  console.log('━━━ ' + (ci + 1) + '. ' + tc.name + '  [' + status + ' ' + pass + '/' + (pass + fail) + '] ━━━');
  console.log('    输出文件: test_output/' + fileName);
  for (var di = 0; di < details.length; di++) console.log(details[di]);
  console.log('');
}

console.log('════════════════════════════════════════════════════');
console.log('  总计: ' + totalCases + ' 项检查, ' + totalPass + ' 通过, ' + totalFail + ' 失败');
console.log('  SQL 文件已保存至 test_output/ 目录, 可直接在对应数据库执行验证');
console.log('════════════════════════════════════════════════════');

process.exit(totalFail > 0 ? 1 : 0);
